# Generated by Django 3.1.6 on 2022-01-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChatLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('room_type', models.CharField(max_length=128)),
                ('room_detail', models.CharField(max_length=128)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=128)),
                ('room_type', models.CharField(max_length=128)),
                ('room_detail', models.CharField(max_length=128)),
                ('channel_name', models.CharField(max_length=128)),
                ('join_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
